### ISSUE TITLE
Error while building IOS app when upgraded from RN 0.64.0 to 0.67.2

### ISSUE THREAD

**Issue by amanraj0505** [vmurin/react-native-azure-auth#161]
Following error while building in IOS

Error: Undefined symbols for architecture x86_64:
  "_RCTMakeError", referenced from:
      -[AzureAuth presentSafariWithURL:] in AzureAuth.o
  "_RCTRegisterModule", referenced from:
      +[AzureAuth load] in AzureAuth.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Package.json**
 "@native-html/table-plugin": "3.1.1",
        "@okta/okta-react-native": "^2.6.0",
        "@react-native-async-storage/async-storage": "^1.17.10",
        "@react-native-firebase/analytics": "^15.7.0",
        "@react-native-firebase/app": "^15.7.0",
        "@react-native-firebase/crashlytics": "^15.7.0",
        "@react-native-firebase/perf": "^15.7.0",
        "@react-native-masked-view/masked-view": "^0.2.5",
        "axios": "^0.21.1",
        "events": "^3.3.0",
        "moment": "^2.29.1",
        "patch-package": "^6.4.7",
        "postinstall-postinstall": "^2.1.0",
        "prop-types": "^15.7.2",
        "react": "17.0.2",
        "react-native": "0.67.2",
        "react-native-actionsheet": "^2.4.2",
        "react-native-aes-crypto": "^2.1.1",
        "react-native-azure-auth": "^1.8.4",
        "react-native-biometrics": "^3.0.1",
        "react-native-calendars": "^1.1267.0",
        "react-native-dialog": "^8.0.1",
        "react-native-fast-image": "^8.3.4",
        "react-native-file-viewer": "^2.1.4",
        "react-native-gesture-handler": "^1.10.3",
        "react-native-i18n": "AlexanderZaytsev/react-native-i18n#master",
        "react-native-image-crop-picker": "^0.36.2",
        "react-native-localization": "^2.1.6",
        "react-native-media-queries": "^0.3.0",
        "react-native-modal": "^11.10.0",
        "react-native-onesignal": "^4.3.11",
        "react-native-reanimated": "^2.1.0",
        "react-native-render-html": "5.1.1",
        "react-native-responsive-screen": "^1.4.2",
        "react-native-safe-area-context": "^3.2.0",
        "react-native-screens": "2.15.2",
        "react-native-status-bar-height": "^2.6.0",
        "react-native-webview": "^11.4.2",
        "react-navigation": "^4.4.4",
        "react-navigation-stack": "^2.10.4",
        "react-navigation-tabs": "^2.11.1",
        "react-redux": "^7.2.3",
        "redux": "^4.0.5",
        "redux-thunk": "^2.3.0",
        "rn-fetch-blob": "^0.10.13",
        "rn-sliding-up-panel": "^2.4.5"

**PodFile:**

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
$RNFirebaseAsStaticFramework = true
platform :ios, '12.4'
target 'mobileapp' do
  config = use_native_modules!
  use_frameworks!
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'mobileappTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
target 'OneSignalNotificationServiceExtension' do
  use_frameworks!
  pod 'OneSignalXCFramework', '>= 3.0', '< 4.0'
end

With the I guess the issue is with the use of use_framework! as i am using the firebase SDK?

**Any suggestion or patch will be highly appreciated**

**Comment by amanraj0505** [comment]
@vmurin any suggestions?

**Comment by vmurin** [comment]
Have you tryed this:

https://react-native-community.github.io/upgrade-helper/?from=0.64.0&to=0.67.2

**Comment by amanraj0505** [comment]
thanks @vmurin issue got resolved now
